#!/bin/sh

# Install homebrew
if ! command -v brew >/dev/null 2>&1; then
  echo "Installing homebrew"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Install vim8
vim_version=$(vim --version | head -1 | egrep -o '[0-9]+\.[0-9]+')
if [ "${vim_version%%.*}" -lt 8 ]; then
  echo "Installing vim8"
  brew install vim --with-override-system-vi
fi

# Install vim-plug
if ! [ -f $HOME/.vim/autoload/plug.vim ]; then
  echo "Installing vim-plug"
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Bootstrapping vim
echo "Bootstrapping vim"
vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
brew install --HEAD universal-ctags/universal-ctags/universal-ctags

# Install n
if ! command -v n >/dev/null 2>&1; then
  echo "Installing node and n"
  curl -L https://git.io/n-install | bash -s -- -y
fi

# Install tmux
if ! command -v tmux >/dev/null 2>&1; then
  echo "Installing tmux"
  brew install tmux reattach-to-user-namespace
fi

# Install iTerm2
install_iterm2_profile () {
  echo "Installing iTerm2 profile"
  defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -int 1
  defaults write com.googlecode.iterm2 PrefsCustomFolder $HOME/.iTerm2
}
if [ -d /Applications/iTerm.app ]; then
  install_iterm2_profile
else
  echo "Installing iTerm2"
  brew cask install iterm2
  install_iterm2_profile
fi

# Update terminfo
echo "Updating terminfo"
curl -O https://raw.githubusercontent.com/nicknisi/dotfiles/master/resources/xterm-256color-italic.terminfo
tic xterm-256color-italic.terminfo
rm xterm-256color-italic.terminfo

# Install zplug
if ! [ -d $HOME/.zplug ]; then
  curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
fi
